[common][api] improve matter api
* Changed return type from CHIP_ERROR to uint8_t for easier integration with C code.
* Introduced new API to explicitly close the commissioning window.
* Added get device information AT command.
* Fixed bug for Matter Shell and Makefile linking.
* Fixed undefined reference to 'mbedtls_memory_buffer_alloc_max_reset' when matter shell is enabled.